plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs

imagemagick:
  enabled: false
